/** Report page behaviour: mounts the Executive Shell from the embedded JSON. */
import { mountExecShell } from './exec-shell.js';

const data = JSON.parse(document.getElementById('report-data').textContent);
const pct = (v) => `${(v * 100).toFixed(1)}%`;

const shell = mountExecShell({
  title: 'Crypto Clustering',
  tagline: `K-means over ${data.coins} coins' price-change profiles with the choice of k made by two stated rules, PCA with its explained variance and loadings, an HDBSCAN comparison that is allowed to call points noise, and an adjusted Rand index between the feature-space and PCA-space clusterings. Generated by CI; nothing is investment advice.`,
  repo: 'https://github.com/Freddricklogan/Crypto-Clustering',
  pagesUrl: 'https://freddricklogan.github.io/Crypto-Clustering/',
  badges: [{ label: 'K-means · PCA · HDBSCAN', tone: 'accent' }, { label: 'Stated rules for k', dot: true }, { label: 'Measured in CI', dot: true }],
  kpis: [
    { label: 'Coins', compute: () => data.coins, tone: 'accent' },
    { label: 'Elbow k / silhouette k', compute: () => `${data.elbowK} / ${data.silhouetteK}` },
    { label: `Silhouette at k=${data.elbowK}`, compute: () => data.silhouetteAtElbow.toFixed(3), tone: 'ok' },
    { label: 'PCA variance (3 PCs)', compute: () => pct(data.explained.reduce((a, b) => a + b, 0)), tone: 'warn' },
    { label: 'HDBSCAN clusters / noise', compute: () => `${data.hdbClusters} / ${data.hdbNoise}`, tone: 'muted' }
  ],
  tour: [
    { selector: '.cc-note', title: 'What this page is', body: `The CI run clustered ${data.coins} coins by seven price-change horizons with seed ${data.seed}. Every table and chart was produced by that run.` },
    { selector: '#s-k', title: 'Two rules, two answers', body: `The knee of the inertia curve says k=${data.elbowK}; the silhouette says k=${data.silhouetteK}. Both are shown with their memberships. Cluster sizes at the elbow are ${data.sizes.join(', ')} — singletons are outliers the method has isolated, not groups.` },
    { selector: '#s-pca', title: 'PCA agrees', body: `Three components keep ${pct(data.explained.reduce((a, b) => a + b, 0))} of the variance, and clustering the scores gives an adjusted Rand index of ${data.ari.toFixed(3)} against the full feature space. The loadings say which horizons drive each component.` },
    { selector: '#s-hdb', title: 'A method that can say "noise"', body: `HDBSCAN found ${data.hdbClusters} dense clusters and left ${data.hdbNoise} coins unassigned. That is a more honest picture of a small, heavy-tailed dataset than forcing every coin into a group.` }
  ]
});
shell.refreshKpis();
